# Generated by Django 6.1.1 on 2026-10-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='doneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.cliente'),
        ),
    ]
